# Generated by Django 4.2.30 on 2026-06-06 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thongbao', '0003_thongbaophathanh_collation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='thongbaophathanh',
            new_name='thong_bao_p_thoi_gi_819ec9_idx',
            old_name='tb_ph_gio_idx',
        ),
        migrations.RenameIndex(
            model_name='thongbaophathanh',
            new_name='thong_bao_p_pham_vi_f55e38_idx',
            old_name='tb_ph_pv_idx',
        ),
        migrations.RenameIndex(
            model_name='thongbaophathanh',
            new_name='thong_bao_p_loai_th_345124_idx',
            old_name='tb_ph_loai_idx',
        ),
        migrations.AlterField(
            model_name='thongbaophathanh',
            name='chuc_vu',
            field=models.CharField(blank=True, help_text='LE_TAN | KHO | ... khi pham_vi=CHUC_VU', max_length=30),
        ),
        migrations.AlterField(
            model_name='thongbaophathanh',
            name='nguoi_nhan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Khi pham_vi=NGUOI_DUNG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thong_bao_phat_hanh_chi_dinh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thongbaophathanh',
            name='vai_tro',
            field=models.CharField(blank=True, help_text='BENH_NHAN | BAC_SI | NHAN_VIEN | ADMIN khi pham_vi=VAI_TRO', max_length=20),
        ),
    ]
