# Generated by Django 4.2.30 on 2026-06-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0003_doctor_schedule_collation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['ngay_lam', 'ca_lam', 'bac_si__ma_bac_si'], 'verbose_name': 'Lịch ca làm bác sĩ', 'verbose_name_plural': 'Lịch ca làm bác sĩ'},
        ),
        migrations.RenameIndex(
            model_name='doctorschedule',
            new_name='doctor_sche_ngay_la_804bec_idx',
            old_name='doctor_sch_ngay_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='doctorschedule',
            new_name='doctor_sche_bac_si__1c34e6_idx',
            old_name='doctor_sch_bs_ngay_idx',
        ),
    ]
